In [3]:
#import libraries
import pandas as pd
import numpy as np

In [4]:
#download first file to discover how it looks
df = pd.read_csv("/Users/ilseeb/Desktop/Postgraduate/Train Punctuality Data/2014/Data_raw_punctuality_201401.csv")

In [5]:
#count how much data we have
df.count()

DATDEP                1900458
TRAIN_NO              1900458
RELATION              1900458
TRAIN_SERV            1900458
PTCAR_NO              1900458
LINE_NO_DEP           1806030
REAL_TIME_ARR         1806067
REAL_TIME_DEP         1806036
PLANNED_TIME_ARR      1806058
PLANNED_TIME_DEP      1806031
DELAY_ARR             1900458
DELAY_DEP             1900458
RELATION_DIRECTION          0
PTCAR_LG_NM_NL        1900458
LINE_NO_ARR           1806064
PLANNED_DATE_ARR      1806058
PLANNED_DATE_DEP      1806031
REAL_DATE_ARR         1806067
REAL_DATE_DEP         1806036
dtype: int64

In [6]:
#look at first 100 rows
df.head(100)

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP
0,01JAN2014,10,ICE,SNCB/NMBS,825,37,20:29:50,20:28:41,20:29:00,20:29:00,-19,-19,NaN,HERGENRATH,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014
1,01JAN2014,10,ICE,SNCB/NMBS,266,37,20:41:26,20:41:26,20:40:00,20:40:00,86,86,NaN,CHENEE,3,01JAN2014,01JAN2014,01JAN2014,01JAN2014
2,01JAN2014,10,ICE,SNCB/NMBS,27,37,20:42:26,20:42:30,20:41:00,20:41:00,86,90,NaN,ANGLEUR,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014
3,01JAN2014,10,ICE,SNCB/NMBS,726,36,20:45:41,20:47:14,20:44:00,20:46:00,101,74,NaN,LIEGE-GUILLEMINS,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014
4,01JAN2014,10,ICE,SNCB/NMBS,31,2,20:51:22,20:51:26,20:51:00,20:51:00,22,26,NaN,ANS,36,01JAN2014,01JAN2014,01JAN2014,01JAN2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,01JAN2014,112,IC/L,SNCB/NMBS,730,34,13:54:34,13:55:38,13:55:00,13:56:00,-26,-22,NaN,LIEGE-PALAIS,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
96,01JAN2014,112,IC/L,SNCB/NMBS,562,34,14:00:20,14:01:29,14:01:00,14:02:00,-40,-31,NaN,HERSTAL,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
97,01JAN2014,112,IC/L,SNCB/NMBS,835,34,14:06:29,14:07:00,14:07:00,14:07:00,-31,0,NaN,MILMORT,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
98,01JAN2014,112,IC/L,SNCB/NMBS,733,34L/1,14:08:40,14:09:01,14:11:00,14:12:00,-140,-179,NaN,LIERS,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
99,01JAN2014,112,IC/L,SNCB/NMBS,734,NaN,14:10:26,NaN,14:16:00,NaN,-334,0,NaN,LIERS-FAISCEAU,34L/1,01JAN2014,NaN,01JAN2014,NaN

In [7]:
#get final destination by grouping per train no. and date of departure
df['destination'] = df.groupby(['DATDEP', 'TRAIN_NO'], sort=False)['PTCAR_LG_NM_NL'].transform('last')

In [8]:
df.head(1220)

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,destination
0,01JAN2014,10,ICE,SNCB/NMBS,825,37,20:29:50,20:28:41,20:29:00,20:29:00,-19,-19,NaN,HERGENRATH,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
1,01JAN2014,10,ICE,SNCB/NMBS,266,37,20:41:26,20:41:26,20:40:00,20:40:00,86,86,NaN,CHENEE,3,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
2,01JAN2014,10,ICE,SNCB/NMBS,27,37,20:42:26,20:42:30,20:41:00,20:41:00,86,90,NaN,ANGLEUR,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
3,01JAN2014,10,ICE,SNCB/NMBS,726,36,20:45:41,20:47:14,20:44:00,20:46:00,101,74,NaN,LIEGE-GUILLEMINS,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
4,01JAN2014,10,ICE,SNCB/NMBS,31,2,20:51:22,20:51:26,20:51:00,20:51:00,22,26,NaN,ANS,36,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,01JAN2014,1508,IC/L,SNCB/NMBS,1670,NaN,11:18:00,NaN,11:19:00,NaN,-60,0,NaN,GENK,21D,01JAN2014,NaN,01JAN2014,NaN,GENK
1216,01JAN2014,1509,IC/L,SNCB/NMBS,642,51B,NaN,9:06:04,NaN,9:04:00,0,124,NaN,KNOKKE,NaN,NaN,01JAN2014,NaN,01JAN2014,GENK
1217,01JAN2014,1509,IC/L,SNCB/NMBS,337,51B,9:09:04,9:09:54,9:07:00,9:07:00,124,174,NaN,DUINBERGEN,51B,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK
1218,01JAN2014,1509,IC/L,SNCB/NMBS,540,51B,9:12:54,9:13:11,9:11:00,9:11:00,114,131,NaN,HEIST,51B,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK
1219,01JAN2014,1509,IC/L,SNCB/NMBS,214,51,9:22:29,9:22:29,9:20:00,9:20:00,149,149,NaN,BRUGGE-DIJK,51,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK

In [9]:
#get only rows where the train departed from BRUSSEL-CENTRAAL
df2 = df[df.PTCAR_LG_NM_NL == 'BRUSSEL-CENTRAAL']

In [10]:
#add column to define if train was delayed or not
df2['delayed'] = np.where(df2['DELAY_DEP'] > 360, True, False)

/var/folders/07/rfr15gnj2vx9fng2s7h5322h0000gn/T/ipykernel_31949/936481568.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['delayed'] = np.where(df2['DELAY_DEP'] > 360, True, False)

In [11]:
df2.count()

DATDEP                31422
TRAIN_NO              31422
RELATION              31422
TRAIN_SERV            31422
PTCAR_NO              31422
LINE_NO_DEP           31422
REAL_TIME_ARR         31422
REAL_TIME_DEP         31422
PLANNED_TIME_ARR      31422
PLANNED_TIME_DEP      31422
DELAY_ARR             31422
DELAY_DEP             31422
RELATION_DIRECTION        0
PTCAR_LG_NM_NL        31422
LINE_NO_ARR           31422
PLANNED_DATE_ARR      31422
PLANNED_DATE_DEP      31422
REAL_DATE_ARR         31422
REAL_DATE_DEP         31422
destination           31422
delayed               31422
dtype: int64