In [21]:
#import libraries
import pandas as pd
import numpy as np

In [22]:
#download first file to discover how it looks
df = pd.read_csv("/Users/ilseeb/Desktop/Postgraduate/Train Punctuality Data/2014/Data_raw_punctuality_201401.csv")

In [23]:
#count how much data we have
df.count()

DATDEP                1900458
TRAIN_NO              1900458
RELATION              1900458
TRAIN_SERV            1900458
PTCAR_NO              1900458
LINE_NO_DEP           1806030
REAL_TIME_ARR         1806067
REAL_TIME_DEP         1806036
PLANNED_TIME_ARR      1806058
PLANNED_TIME_DEP      1806031
DELAY_ARR             1900458
DELAY_DEP             1900458
RELATION_DIRECTION          0
PTCAR_LG_NM_NL        1900458
LINE_NO_ARR           1806064
PLANNED_DATE_ARR      1806058
PLANNED_DATE_DEP      1806031
REAL_DATE_ARR         1806067
REAL_DATE_DEP         1806036
dtype: int64

In [24]:
#look at first 100 rows
df.tail(50)

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP
1900408,31JAN2014,17932,EXTRA,SNCB/NMBS,22,125,19:46:26,19:46:26,18:52:00,18:52:00,3266,3266,NaN,AMAY,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900409,31JAN2014,17932,EXTRA,SNCB/NMBS,530,125,19:48:26,19:48:26,18:54:00,18:54:00,3266,3266,NaN,HAUTE-FLONE,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900410,31JAN2014,17932,EXTRA,SNCB/NMBS,557,125,19:50:26,19:50:26,18:56:00,18:56:00,3266,3266,NaN,HERMALLE-SOUS-HUY,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900411,31JAN2014,17932,EXTRA,SNCB/NMBS,361,125,19:53:26,19:53:26,18:59:00,18:59:00,3266,3266,NaN,ENGIS,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900412,31JAN2014,17932,EXTRA,SNCB/NMBS,402,125,19:56:26,19:56:26,19:02:00,19:02:00,3266,3266,NaN,FLEMALLE-HAUTE,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900413,31JAN2014,17932,EXTRA,SNCB/NMBS,705,125,19:57:26,19:57:26,19:03:00,19:03:00,3266,3266,NaN,LEMAN,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900414,31JAN2014,17932,EXTRA,SNCB/NMBS,401,125,19:57:26,19:57:26,19:03:00,19:03:00,3266,3266,NaN,FLEMALLE-GRANDE,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900415,31JAN2014,17932,EXTRA,SNCB/NMBS,619,125,19:59:26,19:59:26,19:05:00,19:05:00,3266,3266,NaN,JEMEPPE-SUR-MEUSE,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900416,31JAN2014,17932,EXTRA,SNCB/NMBS,971,125,19:59:26,19:59:26,19:05:00,19:05:00,3266,3266,NaN,PONT-DE-SERAING,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900417,31JAN2014,17932,EXTRA,SNCB/NMBS,1148,125,20:00:26,20:00:26,19:06:00,19:06:00,3266,3266,NaN,TILLEUR,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900418,31JAN2014,17932,EXTRA,SNCB/NMBS,1063,125,20:02:26,20:02:26,19:08:00,19:08:00,3266,3266,NaN,SCLESSIN,125,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900419,31JAN2014,17932,EXTRA,SNCB/NMBS,726,NaN,20:04:26,NaN,19:10:00,NaN,3266,0,NaN,LIEGE-GUILLEMINS,125,31JAN2014,NaN,31JAN2014,NaN
1900420,31JAN2014,9470,TGV,SNCB/NMBS,220,96N,NaN,18:29:35,NaN,18:13:00,0,995,NaN,BRUSSEL-ZUID,NaN,NaN,31JAN2014,NaN,31JAN2014
1900421,31JAN2014,9470,TGV,SNCB/NMBS,504,1,18:36:38,18:36:38,18:17:00,18:17:00,1178,1178,NaN,HALLE,1,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900422,31JAN2014,17949,EXTRA,SNCB/NMBS,1691,50L/7,NaN,20:00:00,NaN,20:00:00,0,0,NaN,MERELBEKE-T.W.,NaN,NaN,31JAN2014,NaN,31JAN2014
1900423,31JAN2014,17949,EXTRA,SNCB/NMBS,1386,50L/1,20:02:00,20:10:00,20:02:00,20:10:00,0,0,NaN,MERELBEKE-SAS T.W.,50L/7,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900424,31JAN2014,17949,EXTRA,SNCB/NMBS,455,75,20:09:55,20:13:39,20:19:00,20:19:00,-545,-321,NaN,GENT-SINT-PIETERS,50,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900425,31JAN2014,17949,EXTRA,SNCB/NMBS,320,75,20:19:33,20:19:59,20:25:00,20:25:00,-327,-301,NaN,DE PINTE,75,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900426,31JAN2014,17949,EXTRA,SNCB/NMBS,93,75,20:23:59,20:24:20,20:31:00,20:31:00,-421,-400,NaN,DEINZE-WIJKSPOREN,75,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900427,31JAN2014,17949,EXTRA,SNCB/NMBS,317,75,20:24:50,20:25:33,20:32:00,20:32:00,-430,-387,NaN,DEINZE,75,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900428,31JAN2014,17949,EXTRA,SNCB/NMBS,1212,75,20:33:51,20:34:22,20:42:00,20:42:00,-489,-458,NaN,WAREGEM,75,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900429,31JAN2014,17949,EXTRA,SNCB/NMBS,520,75,20:42:22,20:42:22,20:50:00,20:50:00,-458,-458,NaN,HARELBEKE,75,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900430,31JAN2014,17949,EXTRA,SNCB/NMBS,649,NaN,20:49:00,NaN,20:55:00,NaN,-360,0,NaN,KORTRIJK,75,31JAN2014,NaN,31JAN2014,NaN
1900431,31JAN2014,17930,EXTRA,SNCB/NMBS,455,50E,NaN,23:29:27,NaN,22:15:00,0,4467,NaN,GENT-SINT-PIETERS,NaN,NaN,31JAN2014,NaN,31JAN2014
1900432,31JAN2014,17930,EXTRA,SNCB/NMBS,1386,50L/7,23:34:03,23:42:03,22:17:00,22:25:00,4623,4623,NaN,MERELBEKE-SAS T.W.,50L/1,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900433,31JAN2014,17930,EXTRA,SNCB/NMBS,1691,NaN,22:26:00,NaN,22:26:00,NaN,4623,0,NaN,MERELBEKE-T.W.,50L/7,31JAN2014,NaN,31JAN2014,NaN
1900434,31JAN2014,17951,EXTRA,SNCB/NMBS,640,125C,NaN,22:40:03,NaN,22:30:00,0,603,NaN,KINKEMPOIS-A.T.,NaN,NaN,31JAN2014,NaN,31JAN2014
1900435,31JAN2014,17951,EXTRA,SNCB/NMBS,726,NaN,22:45:51,NaN,22:34:00,NaN,711,0,NaN,LIEGE-GUILLEMINS,37A,31JAN2014,NaN,31JAN2014,NaN
1900436,31JAN2014,17953,EXTRA,SNCB/NMBS,504,96,NaN,23:41:24,NaN,23:28:00,0,804,NaN,HALLE,NaN,NaN,31JAN2014,NaN,31JAN2014
1900437,31JAN2014,17953,EXTRA,SNCB/NMBS,232,96,23:43:50,23:43:50,23:31:00,23:31:00,770,770,NaN,BUIZINGEN,96,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900438,31JAN2014,17953,EXTRA,SNCB/NMBS,759,96,23:44:48,23:44:48,23:33:00,23:33:00,708,708,NaN,LOT,96,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900439,31JAN2014,17953,EXTRA,SNCB/NMBS,1021,96,23:47:48,23:47:48,23:36:00,23:36:00,708,708,NaN,RUISBROEK,96,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900440,31JAN2014,17953,EXTRA,SNCB/NMBS,415,96,23:48:41,23:48:41,23:39:00,23:39:00,581,581,NaN,VORST-ZUID,96,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900441,31JAN2014,17953,EXTRA,SNCB/NMBS,220,0/3,23:51:35,23:55:51,23:42:00,23:42:00,575,831,NaN,BRUSSEL-ZUID,96,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900442,31JAN2014,17953,EXTRA,SNCB/NMBS,217,0/3,23:58:29,23:58:06,23:44:00,23:44:00,869,846,NaN,BRUSSEL-KAPELLEKERK,0/3,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900443,31JAN2014,17953,EXTRA,SNCB/NMBS,215,0/3,23:58:59,23:58:52,23:45:00,23:45:00,839,832,NaN,BRUSSEL-CENTRAAL,0/3,31JAN2014,31JAN2014,31JAN2014,31JAN2014
1900444,31JAN2014,17953,EXTRA,SNCB/NMBS,216,0/3,0:00:05,0:00:03,23:46:00,23:46:00,845,843,NaN,BRUSSEL-CONGRES,0/3,31JAN2014,31JAN2014,01FEB2014,01FEB2014
1900445,31JAN2014,17953,EXTRA,SNCB/NMBS,221,161/2,0:01:40,0:01:56,23:48:00,23:48:00,820,836,NaN,BRUSSEL-NOORD,0/3,31JAN2014,31JAN2014,01FEB2014,01FEB2014
1900446,31JAN2014,17953,EXTRA,SNCB/NMBS,227,161,0:08:21,0:08:21,23:53:00,23:53:00,921,921,NaN,BRUSSEL-SCHUMAN,161,31JAN2014,31JAN2014,01FEB2014,01FEB2014
1900447,31JAN2014,17953,EXTRA,SNCB/NMBS,218,161,0:09:32,0:09:40,23:54:00,23:54:00,932,940,NaN,BRUSSEL-LUXEMBURG,161,31JAN2014,31JAN2014,01FEB2014,01FEB2014
1900448,31JAN2014,17953,EXTRA,SNCB/NMBS,380,161,0:12:14,0:12:33,23:57:00,23:57:00,914,933,NaN,ETTERBEEK,161,31JAN2014,31JAN2014,01FEB2014,01FEB2014
1900449,31JAN2014,17953,EXTRA,SNCB/NMBS,1219,161,0:16:33,0:14:06,0:01:00,0:01:00,933,786,NaN,WATERMAAL,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900450,31JAN2014,17953,EXTRA,SNCB/NMBS,183,161,0:16:06,0:15:17,0:03:00,0:03:00,786,737,NaN,BOSVOORDE,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900451,31JAN2014,17953,EXTRA,SNCB/NMBS,486,161,0:17:32,0:17:35,0:08:00,0:08:00,572,575,NaN,GROENENDAAL,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900452,31JAN2014,17953,EXTRA,SNCB/NMBS,572,161,0:19:32,0:19:35,0:10:00,0:10:00,575,575,NaN,HOEILAART,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900453,31JAN2014,17953,EXTRA,SNCB/NMBS,672,161,0:20:00,0:19:56,0:14:00,0:14:00,360,356,NaN,LA HULPE,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900454,31JAN2014,17953,EXTRA,SNCB/NMBS,457,161,0:22:56,0:20:52,0:17:00,0:17:00,356,232,NaN,GENVAL,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900455,31JAN2014,17953,EXTRA,SNCB/NMBS,997,161,0:21:49,0:21:54,0:20:00,0:20:00,109,114,NaN,RIXENSART,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900456,31JAN2014,17953,EXTRA,SNCB/NMBS,975,161,0:24:54,0:23:05,0:23:00,0:23:00,114,5,NaN,PROFONDSART,161,01FEB2014,01FEB2014,01FEB2014,01FEB2014
1900457,31JAN2014,17953,EXTRA,SNCB/NMBS,936,NaN,0:25:54,NaN,0:26:00,NaN,-6,0,NaN,OTTIGNIES,161,01FEB2014,NaN,01FEB2014,NaN

In [25]:
#get final destination by grouping per train no. and date of departure
df['destination'] = df.groupby(['DATDEP', 'TRAIN_NO'], sort=False)['PTCAR_LG_NM_NL'].transform('last')

In [26]:
#get departure station by grouping per train no. and date of departure
df['departure'] = df.groupby(['DATDEP', 'TRAIN_NO'], sort=False)['PTCAR_LG_NM_NL'].transform('first')

In [27]:
df.head(1220)

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,...,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,destination,departure
0,01JAN2014,10,ICE,SNCB/NMBS,825,37,20:29:50,20:28:41,20:29:00,20:29:00,...,-19,NaN,HERGENRATH,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,HERGENRATH
1,01JAN2014,10,ICE,SNCB/NMBS,266,37,20:41:26,20:41:26,20:40:00,20:40:00,...,86,NaN,CHENEE,3,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,HERGENRATH
2,01JAN2014,10,ICE,SNCB/NMBS,27,37,20:42:26,20:42:30,20:41:00,20:41:00,...,90,NaN,ANGLEUR,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,HERGENRATH
3,01JAN2014,10,ICE,SNCB/NMBS,726,36,20:45:41,20:47:14,20:44:00,20:46:00,...,74,NaN,LIEGE-GUILLEMINS,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,HERGENRATH
4,01JAN2014,10,ICE,SNCB/NMBS,31,2,20:51:22,20:51:26,20:51:00,20:51:00,...,26,NaN,ANS,36,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,HERGENRATH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,01JAN2014,1508,IC/L,SNCB/NMBS,1670,NaN,11:18:00,NaN,11:19:00,NaN,...,0,NaN,GENK,21D,01JAN2014,NaN,01JAN2014,NaN,GENK,KNOKKE
1216,01JAN2014,1509,IC/L,SNCB/NMBS,642,51B,NaN,9:06:04,NaN,9:04:00,...,124,NaN,KNOKKE,NaN,NaN,01JAN2014,NaN,01JAN2014,GENK,KNOKKE
1217,01JAN2014,1509,IC/L,SNCB/NMBS,337,51B,9:09:04,9:09:54,9:07:00,9:07:00,...,174,NaN,DUINBERGEN,51B,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK,KNOKKE
1218,01JAN2014,1509,IC/L,SNCB/NMBS,540,51B,9:12:54,9:13:11,9:11:00,9:11:00,...,131,NaN,HEIST,51B,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK,KNOKKE
1219,01JAN2014,1509,IC/L,SNCB/NMBS,214,51,9:22:29,9:22:29,9:20:00,9:20:00,...,149,NaN,BRUGGE-DIJK,51,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK,KNOKKE

In [28]:
#get only rows where the train departed from BRUSSEL-CENTRAAL
df2 = df[df.PTCAR_LG_NM_NL == 'BRUSSEL-CENTRAAL']

In [29]:
#add column to define if train was delayed or not
df2['delayed'] = np.where(df2['DELAY_DEP'] > 360, True, False)

/var/folders/07/rfr15gnj2vx9fng2s7h5322h0000gn/T/ipykernel_31949/936481568.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['delayed'] = np.where(df2['DELAY_DEP'] > 360, True, False)

In [30]:
df2.count()

DATDEP                31422
TRAIN_NO              31422
RELATION              31422
TRAIN_SERV            31422
PTCAR_NO              31422
LINE_NO_DEP           31422
REAL_TIME_ARR         31422
REAL_TIME_DEP         31422
PLANNED_TIME_ARR      31422
PLANNED_TIME_DEP      31422
DELAY_ARR             31422
DELAY_DEP             31422
RELATION_DIRECTION        0
PTCAR_LG_NM_NL        31422
LINE_NO_ARR           31422
PLANNED_DATE_ARR      31422
PLANNED_DATE_DEP      31422
REAL_DATE_ARR         31422
REAL_DATE_DEP         31422
destination           31422
departure             31422
delayed               31422
dtype: int64