In [21]:
#import libraries
import pandas as pd
import numpy as np
pd.set_option('display.expand_frame_repr', False)

In [22]:
# import file
df = pd.read_pickle("/Users/ilseeb/Desktop/Postgraduate/Train Punctuality Data/final_df.pkl")

In [23]:
df.head()

  TRAIN_NO RELATION TRAIN_SERV PTCAR_NO LINE_NO_DEP REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP DELAY_ARR  ...  year month day hour_time_dep       destination_region         departure_region temperature relative_humidity wind_speed wind_direction
0       10      ICE  SNCB/NMBS      215         0/2      21:31:15      21:31:07         21:32:00         21:32:00       -45  ...  2014     1   1          22.0  BRUSSELS-CAPITAL REGION                 WALLONIA         9.0              84.0       35.0           18.0
1     1209      INT  SNCB/NMBS      215         0/6       9:58:51      10:01:11          9:59:00         10:01:00        -9  ...  2014     1   1          10.0  BRUSSELS-CAPITAL REGION                 FLANDERS         6.0              86.0       23.0           18.0
2     1210      INT  SNCB/NMBS      215         0/5       7:02:34       7:04:17          6:59:00          7:01:00       214  ...  2014     1   1           7.0                 FLANDERS  BRUSSELS-CAPITAL REGION         5.0              89.0       21.0           19.0
3     1213      INT  SNCB/NMBS      215         0/6      10:57:53      11:00:59         10:59:00         11:01:00       -67  ...  2014     1   1          11.0  BRUSSELS-CAPITAL REGION                 FLANDERS         6.0              83.0       23.0           17.0
4     1217      INT  SNCB/NMBS      215         0/6      11:58:12      12:03:39         11:59:00         12:01:00       -48  ...  2014     1   1          12.0  BRUSSELS-CAPITAL REGION                 FLANDERS         7.0              82.0       22.0           17.0

[5 rows x 31 columns]

In [24]:
df = df.drop(columns=["TRAIN_NO", "RELATION", "PTCAR_NO", "LINE_NO_DEP"
                    , "RELATION_DIRECTION", "LINE_NO_ARR", "PLANNED_DATE_ARR"
                    , "PLANNED_DATE_DEP", "REAL_DATE_ARR", "REAL_DATE_DEP"
                    ,"PTCAR_LG_NM_NL"])

In [25]:
df.head()

  TRAIN_SERV REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP DELAY_ARR DELAY_DEP     departure   destination delayed  year  month  day  hour_time_dep       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction
0  SNCB/NMBS      21:31:15      21:31:07         21:32:00         21:32:00       -45       -53    HERGENRATH  BRUSSEL-ZUID   False  2014      1    1           22.0  BRUSSELS-CAPITAL REGION                 WALLONIA          9.0               84.0        35.0            18.0
1  SNCB/NMBS       9:58:51      10:01:11          9:59:00         10:01:00        -9        11         ESSEN  BRUSSEL-ZUID   False  2014      1    1           10.0  BRUSSELS-CAPITAL REGION                 FLANDERS          6.0               86.0        23.0            18.0
2  SNCB/NMBS       7:02:34       7:04:17          6:59:00          7:01:00       214       197  BRUSSEL-ZUID         ESSEN   False  2014      1    1            7.0                 FLANDERS  BRUSSELS-CAPITAL REGION          5.0               89.0        21.0            19.0
3  SNCB/NMBS      10:57:53      11:00:59         10:59:00         11:01:00       -67        -1         ESSEN  BRUSSEL-ZUID   False  2014      1    1           11.0  BRUSSELS-CAPITAL REGION                 FLANDERS          6.0               83.0        23.0            17.0
4  SNCB/NMBS      11:58:12      12:03:39         11:59:00         12:01:00       -48       159         ESSEN  BRUSSEL-ZUID   False  2014      1    1           12.0  BRUSSELS-CAPITAL REGION                 FLANDERS          7.0               82.0        22.0            17.0

In [26]:
df.describe(include="all")

       TRAIN_SERV REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP  DELAY_ARR  DELAY_DEP     departure   destination  delayed          year         month           day  hour_time_dep destination_region departure_region   temperature  relative_humidity    wind_speed  wind_direction
count     3183238       3183218       3183097          3182701          3182569  3183231.0  3183160.0       3183238       3183238  3183238  3.183238e+06  3.183238e+06  3.183238e+06   3.182569e+06            3183238          3183238  3.182569e+06       3.182569e+06  3.182569e+06    3.182569e+06
unique          5         73782         73830             5656             5491     7273.0     7318.0           294           432        2           NaN           NaN           NaN            NaN                  3                3           NaN                NaN           NaN             NaN
top     SNCB/NMBS      21:22:27      14:28:20         17:31:00          9:01:00       25.0       19.0  BRUSSEL-ZUID  BRUSSEL-ZUID    False           NaN           NaN           NaN            NaN           FLANDERS         FLANDERS           NaN                NaN           NaN             NaN
freq      3095982           123           122            10013             8414    22608.0    19062.0        491917        492829  2753997           NaN           NaN           NaN            NaN            1426306          1428004           NaN                NaN           NaN             NaN
mean          NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.017983e+03  6.519606e+00  1.572966e+01   1.395110e+01                NaN              NaN  1.187664e+01       7.525820e+01  1.388163e+01    2.819773e+01
std           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.585676e+00  3.456399e+00  8.763564e+00   5.289505e+00                NaN              NaN  6.922858e+00       1.619571e+01  7.230247e+00    1.682223e+01
min           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.014000e+03  1.000000e+00  1.000000e+00   0.000000e+00                NaN              NaN -9.000000e+00       1.000000e+01  0.000000e+00    0.000000e+00
25%           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.016000e+03  3.000000e+00  8.000000e+00   9.000000e+00                NaN              NaN  7.000000e+00       6.400000e+01  8.000000e+00    1.900000e+01
50%           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.018000e+03  7.000000e+00  1.600000e+01   1.400000e+01                NaN              NaN  1.200000e+01       7.900000e+01  1.300000e+01    2.300000e+01
75%           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.020000e+03  1.000000e+01  2.300000e+01   1.800000e+01                NaN              NaN  1.700000e+01       8.900000e+01  1.800000e+01    3.100000e+01
max           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.022000e+03  1.200000e+01  3.100000e+01   2.300000e+01                NaN              NaN  3.900000e+01       9.900000e+01  5.400000e+01    9.900000e+01