In [29]:
#import libraries
import pandas as pd
import numpy as np
pd.set_option('display.expand_frame_repr', False)

In [30]:
# import file
df = pd.read_pickle("/Users/ilseeb/Desktop/Postgraduate/Train Punctuality Data/final_df.pkl")

In [31]:
df.head()

  TRAIN_NO RELATION TRAIN_SERV PTCAR_NO LINE_NO_DEP REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP DELAY_ARR DELAY_DEP RELATION_DIRECTION    PTCAR_LG_NM_NL LINE_NO_ARR PLANNED_DATE_ARR PLANNED_DATE_DEP REAL_DATE_ARR REAL_DATE_DEP     departure   destination delayed  year  month  day  hour_time_dep       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction
0       10      ICE  SNCB/NMBS      215         0/2      21:31:15      21:31:07         21:32:00         21:32:00       -45       -53                NaN  BRUSSEL-CENTRAAL         0/2        01JAN2014        01JAN2014     01JAN2014     01JAN2014    HERGENRATH  BRUSSEL-ZUID   False  2014      1    1           22.0  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713
1     1209      INT  SNCB/NMBS      215         0/6       9:58:51      10:01:11          9:59:00         10:01:00        -9        11                NaN  BRUSSEL-CENTRAAL         0/6        01JAN2014        01JAN2014     01JAN2014     01JAN2014         ESSEN  BRUSSEL-ZUID   False  2014      1    1           10.0  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257
2     1210      INT  SNCB/NMBS      215         0/5       7:02:34       7:04:17          6:59:00          7:01:00       214       197                NaN  BRUSSEL-CENTRAAL         0/5        01JAN2014        01JAN2014     01JAN2014     01JAN2014  BRUSSEL-ZUID         ESSEN   False  2014      1    1            7.0                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595
3     1213      INT  SNCB/NMBS      215         0/6      10:57:53      11:00:59         10:59:00         11:01:00       -67        -1                NaN  BRUSSEL-CENTRAAL         0/6        01JAN2014        01JAN2014     01JAN2014     01JAN2014         ESSEN  BRUSSEL-ZUID   False  2014      1    1           11.0  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430
4     1217      INT  SNCB/NMBS      215         0/6      11:58:12      12:03:39         11:59:00         12:01:00       -48       159                NaN  BRUSSEL-CENTRAAL         0/6        01JAN2014        01JAN2014     01JAN2014     01JAN2014         ESSEN  BRUSSEL-ZUID   False  2014      1    1           12.0  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006

In [32]:
# drop columns that will not be used for analysis

df = df.drop(columns=["TRAIN_NO", "RELATION", "PTCAR_NO", "LINE_NO_DEP"
                    , "RELATION_DIRECTION", "LINE_NO_ARR", "PLANNED_DATE_ARR"
                    , "PLANNED_DATE_DEP", "REAL_DATE_ARR", "REAL_DATE_DEP"
                    ,"PTCAR_LG_NM_NL"])

In [33]:
df.head()

  TRAIN_SERV REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP DELAY_ARR DELAY_DEP     departure   destination delayed  year  month  day  hour_time_dep       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction
0  SNCB/NMBS      21:31:15      21:31:07         21:32:00         21:32:00       -45       -53    HERGENRATH  BRUSSEL-ZUID   False  2014      1    1           22.0  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713
1  SNCB/NMBS       9:58:51      10:01:11          9:59:00         10:01:00        -9        11         ESSEN  BRUSSEL-ZUID   False  2014      1    1           10.0  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257
2  SNCB/NMBS       7:02:34       7:04:17          6:59:00          7:01:00       214       197  BRUSSEL-ZUID         ESSEN   False  2014      1    1            7.0                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595
3  SNCB/NMBS      10:57:53      11:00:59         10:59:00         11:01:00       -67        -1         ESSEN  BRUSSEL-ZUID   False  2014      1    1           11.0  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430
4  SNCB/NMBS      11:58:12      12:03:39         11:59:00         12:01:00       -48       159         ESSEN  BRUSSEL-ZUID   False  2014      1    1           12.0  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006

In [34]:
#check which columns have nulls

df.describe(include="all")

       TRAIN_SERV REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP  DELAY_ARR  DELAY_DEP     departure   destination  delayed          year         month           day  hour_time_dep destination_region departure_region   temperature  relative_humidity    wind_speed  wind_direction
count     3183238       3183218       3183097          3182701          3182569  3183231.0  3183160.0       3183238       3183238  3183238  3.183238e+06  3.183238e+06  3.183238e+06   3.182569e+06            3183238          3183238  3.182569e+06       3.182569e+06  3.182569e+06    3.182569e+06
unique          5         73782         73830             5656             5491     7273.0     7318.0           294           432        2           NaN           NaN           NaN            NaN                  3                3           NaN                NaN           NaN             NaN
top     SNCB/NMBS      21:22:27      14:28:20         17:31:00          9:01:00       25.0       19.0  BRUSSEL-ZUID  BRUSSEL-ZUID    False           NaN           NaN           NaN            NaN           FLANDERS         FLANDERS           NaN                NaN           NaN             NaN
freq      3095982           123           122            10013             8414    22608.0    19062.0        491917        492829  2753997           NaN           NaN           NaN            NaN            1426306          1428004           NaN                NaN           NaN             NaN
mean          NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.017983e+03  6.519606e+00  1.572966e+01   1.395110e+01                NaN              NaN  1.234741e+01       7.580092e+01  1.438162e+01    1.926267e+02
std           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.585676e+00  3.456399e+00  8.763564e+00   5.289505e+00                NaN              NaN  6.969054e+00       1.614131e+01  7.223310e+00    9.139926e+01
min           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.014000e+03  1.000000e+00  1.000000e+00   0.000000e+00                NaN              NaN -9.139056e+00       1.593023e+01  0.000000e+00    9.391785e-01
25%           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.016000e+03  3.000000e+00  8.000000e+00   9.000000e+00                NaN              NaN  7.040944e+00       6.463734e+01  8.913181e+00    1.310548e+02
50%           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.018000e+03  7.000000e+00  1.600000e+01   1.400000e+01                NaN              NaN  1.206094e+01       7.932415e+01  1.323704e+01    2.105297e+02
75%           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.020000e+03  1.000000e+01  2.300000e+01   1.800000e+01                NaN              NaN  1.735094e+01       8.924670e+01  1.859845e+01    2.513331e+02
max           NaN           NaN           NaN              NaN              NaN        NaN        NaN           NaN           NaN      NaN  2.022000e+03  1.200000e+01  3.100000e+01   2.300000e+01                NaN              NaN  3.913095e+01       1.001186e+02  5.408393e+01    3.600000e+02

In [35]:
# create a list of our conditions
conditions = [
    (df["hour_time_dep"] < 6),
    (df["hour_time_dep"] >= 6) &  (df["hour_time_dep"] < 12),
    (df["hour_time_dep"] >= 12) &  (df["hour_time_dep"] < 18),
    (df["hour_time_dep"] >= 18),
    ]

# create a list of the values we want to assign for each condition
values = ["night", "morning", "afternoon", "night"]

# create a new column and use np.select to assign values to it using our lists as arguments
df["time_of_day"] = np.select(conditions, values)

# display updated DataFrame
df.head()

  TRAIN_SERV REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP DELAY_ARR DELAY_DEP     departure   destination delayed  year  month  day  hour_time_dep       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day
0  SNCB/NMBS      21:31:15      21:31:07         21:32:00         21:32:00       -45       -53    HERGENRATH  BRUSSEL-ZUID   False  2014      1    1           22.0  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713       night
1  SNCB/NMBS       9:58:51      10:01:11          9:59:00         10:01:00        -9        11         ESSEN  BRUSSEL-ZUID   False  2014      1    1           10.0  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257     morning
2  SNCB/NMBS       7:02:34       7:04:17          6:59:00          7:01:00       214       197  BRUSSEL-ZUID         ESSEN   False  2014      1    1            7.0                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595     morning
3  SNCB/NMBS      10:57:53      11:00:59         10:59:00         11:01:00       -67        -1         ESSEN  BRUSSEL-ZUID   False  2014      1    1           11.0  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430     morning
4  SNCB/NMBS      11:58:12      12:03:39         11:59:00         12:01:00       -48       159         ESSEN  BRUSSEL-ZUID   False  2014      1    1           12.0  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006   afternoon

In [36]:
# set option for pandas to display all columns at once
pd.set_option('display.max_columns', 500)

In [37]:
# analyze rows where the temperature is null
df[df["temperature"].isnull()]

        TRAIN_SERV REAL_TIME_ARR REAL_TIME_DEP PLANNED_TIME_ARR PLANNED_TIME_DEP DELAY_ARR DELAY_DEP                    departure       destination delayed  year  month  day  hour_time_dep       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day
34119    SNCB/NMBS      14:39:39           NaN         14:28:00              NaN       699      1891                 BRUSSEL-ZUID  BRUSSEL-CENTRAAL    True  2014      2    4            NaN  BRUSSELS-CAPITAL REGION  BRUSSELS-CAPITAL REGION          NaN                NaN         NaN             NaN           0
35143    SNCB/NMBS      16:01:17           NaN         15:26:00              NaN      2117         0              VORST-RIJTUIGEN  BRUSSEL-CENTRAAL   False  2014      2    4            NaN  BRUSSELS-CAPITAL REGION  BRUSSELS-CAPITAL REGION          NaN                NaN         NaN             NaN           0
97082    SNCB/NMBS       7:57:44           NaN          7:52:00              NaN       344      1958           ANTWERPEN-CENTRAAL  BRUSSEL-CENTRAAL    True  2014      4    7            NaN  BRUSSELS-CAPITAL REGION                 FLANDERS          NaN                NaN         NaN             NaN           0
132350   SNCB/NMBS      23:17:35           NaN         23:14:00              NaN       215       215  LOUVAIN-LA-NEUVE-UNIVERSITE  BRUSSEL-CENTRAAL   False  2014      5   12            NaN  BRUSSELS-CAPITAL REGION                 WALLONIA          NaN                NaN         NaN             NaN           0
137025   SNCB/NMBS      22:47:33           NaN         22:47:00              NaN        33        33                        ARLON  BRUSSEL-CENTRAAL   False  2014      5   16            NaN  BRUSSELS-CAPITAL REGION                 WALLONIA          NaN                NaN         NaN             NaN           0
...            ...           ...           ...              ...              ...       ...       ...                          ...               ...     ...   ...    ...  ...            ...                      ...                      ...          ...                ...         ...             ...         ...
2998360  SNCB/NMBS      19:19:13           NaN         18:12:00              NaN    4033.0       NaN                NOORDERKEMPEN  BRUSSEL-CENTRAAL   False  2022      6   23            NaN  BRUSSELS-CAPITAL REGION                 FLANDERS          NaN                NaN         NaN             NaN           0
3060851  SNCB/NMBS      22:37:38           NaN         22:37:00              NaN      38.0       NaN                 BRUSSEL-ZUID  BRUSSEL-CENTRAAL   False  2022      8   26            NaN  BRUSSELS-CAPITAL REGION  BRUSSELS-CAPITAL REGION          NaN                NaN         NaN             NaN           0
3100580  SNCB/NMBS       5:49:33           NaN          5:49:00              NaN      33.0       NaN                 BRUSSEL-ZUID  BRUSSEL-CENTRAAL   False  2022     10    5            NaN  BRUSSELS-CAPITAL REGION  BRUSSELS-CAPITAL REGION          NaN                NaN         NaN             NaN           0
3112351  SNCB/NMBS       9:24:38           NaN          7:47:00              NaN    5858.0       NaN  BRUSSELS AIRPORT - ZAVENTEM  BRUSSEL-CENTRAAL   False  2022     10   17            NaN  BRUSSELS-CAPITAL REGION  BRUSSELS-CAPITAL REGION          NaN                NaN         NaN             NaN           0
3164569  SNCB/NMBS      20:14:12           NaN         19:31:00              NaN    2592.0       NaN                   HERGENRATH  BRUSSEL-CENTRAAL   False  2022     12   13            NaN  BRUSSELS-CAPITAL REGION                 WALLONIA          NaN                NaN         NaN             NaN           0

[669 rows x 21 columns]

In [38]:
# delete all rows where the temperature is null
df.dropna(subset=["temperature"], inplace=True)

In [39]:
df.count()

TRAIN_SERV            3182569
REAL_TIME_ARR         3182550
REAL_TIME_DEP         3182569
PLANNED_TIME_ARR      3182541
PLANNED_TIME_DEP      3182569
DELAY_ARR             3182562
DELAY_DEP             3182569
departure             3182569
destination           3182569
delayed               3182569
year                  3182569
month                 3182569
day                   3182569
hour_time_dep         3182569
destination_region    3182569
departure_region      3182569
temperature           3182569
relative_humidity     3182569
wind_speed            3182569
wind_direction        3182569
time_of_day           3182569
dtype: int64

In [40]:
df.dropna(subset=["PLANNED_TIME_ARR"], inplace=True)

In [41]:
df.count()

TRAIN_SERV            3182541
REAL_TIME_ARR         3182541
REAL_TIME_DEP         3182541
PLANNED_TIME_ARR      3182541
PLANNED_TIME_DEP      3182541
DELAY_ARR             3182541
DELAY_DEP             3182541
departure             3182541
destination           3182541
delayed               3182541
year                  3182541
month                 3182541
day                   3182541
hour_time_dep         3182541
destination_region    3182541
departure_region      3182541
temperature           3182541
relative_humidity     3182541
wind_speed            3182541
wind_direction        3182541
time_of_day           3182541
dtype: int64

In [42]:
df = df.drop(columns=["REAL_TIME_ARR", "REAL_TIME_DEP", "PLANNED_TIME_ARR"
                    , "PLANNED_TIME_DEP", "DELAY_ARR", "departure", "destination"
                    , "hour_time_dep"])

In [43]:
df.head()

  TRAIN_SERV DELAY_DEP delayed  year  month  day       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day
0  SNCB/NMBS       -53   False  2014      1    1  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713       night
1  SNCB/NMBS        11   False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257     morning
2  SNCB/NMBS       197   False  2014      1    1                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595     morning
3  SNCB/NMBS        -1   False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430     morning
4  SNCB/NMBS       159   False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006   afternoon

In [44]:
df.dtypes

TRAIN_SERV             object
DELAY_DEP              object
delayed                object
year                    int64
month                   int64
day                     int64
destination_region     object
departure_region       object
temperature           float64
relative_humidity     float64
wind_speed            float64
wind_direction        float64
time_of_day            object
dtype: object

In [45]:
df.describe(include="all")

       TRAIN_SERV  DELAY_DEP  delayed          year         month           day destination_region departure_region   temperature  relative_humidity    wind_speed  wind_direction time_of_day
count     3182541  3182541.0  3182541  3.182541e+06  3.182541e+06  3.182541e+06            3182541          3182541  3.182541e+06       3.182541e+06  3.182541e+06    3.182541e+06     3182541
unique          5     7316.0        2           NaN           NaN           NaN                  3                3           NaN                NaN           NaN             NaN           3
top     SNCB/NMBS       19.0    False           NaN           NaN           NaN           FLANDERS         FLANDERS           NaN                NaN           NaN             NaN   afternoon
freq      3095293    19057.0  2753417           NaN           NaN           NaN            1426092          1427759           NaN                NaN           NaN             NaN     1090749
mean          NaN        NaN      NaN  2.017983e+03  6.519619e+00  1.572875e+01                NaN              NaN  1.234745e+01       7.580078e+01  1.438161e+01    1.926267e+02         NaN
std           NaN        NaN      NaN  2.585762e+00  3.456644e+00  8.763777e+00                NaN              NaN  6.969058e+00       1.614129e+01  7.223333e+00    9.139962e+01         NaN
min           NaN        NaN      NaN  2.014000e+03  1.000000e+00  1.000000e+00                NaN              NaN -9.139056e+00       1.593023e+01  0.000000e+00    9.391785e-01         NaN
25%           NaN        NaN      NaN  2.016000e+03  3.000000e+00  8.000000e+00                NaN              NaN  7.040944e+00       6.463734e+01  8.913181e+00    1.310548e+02         NaN
50%           NaN        NaN      NaN  2.018000e+03  7.000000e+00  1.600000e+01                NaN              NaN  1.206094e+01       7.932415e+01  1.323704e+01    2.105297e+02         NaN
75%           NaN        NaN      NaN  2.020000e+03  1.000000e+01  2.300000e+01                NaN              NaN  1.735094e+01       8.924670e+01  1.859845e+01    2.513331e+02         NaN
max           NaN        NaN      NaN  2.022000e+03  1.200000e+01  3.100000e+01                NaN              NaN  3.913095e+01       1.001186e+02  5.408393e+01    3.600000e+02         NaN

In [46]:
# change data types
df["TRAIN_SERV"] = df["TRAIN_SERV"].astype(str)
df["DELAY_DEP"] = pd.to_numeric(df["DELAY_DEP"])
df["delayed"] = df["delayed"].astype(bool)
df["destination_region"] = df["destination_region"].astype(str)
df["departure_region"] = df["departure_region"].astype(str)
df["time_of_day"] = df["time_of_day"].astype(str)

In [47]:
df.dtypes

TRAIN_SERV             object
DELAY_DEP               int64
delayed                  bool
year                    int64
month                   int64
day                     int64
destination_region     object
departure_region       object
temperature           float64
relative_humidity     float64
wind_speed            float64
wind_direction        float64
time_of_day            object
dtype: object

In [48]:
df.rename(columns={"TRAIN_SERV":"train_serv", "DELAY_DEP":"delay_dep"}, inplace=True)

In [49]:
df.head()

  train_serv  delay_dep  delayed  year  month  day       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day
0  SNCB/NMBS        -53    False  2014      1    1  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713       night
1  SNCB/NMBS         11    False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257     morning
2  SNCB/NMBS        197    False  2014      1    1                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595     morning
3  SNCB/NMBS         -1    False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430     morning
4  SNCB/NMBS        159    False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006   afternoon

In [50]:
df["date"] = df["day"].astype(str) + "-" + df["month"].astype(str) + "-" + df["year"].astype(str)

In [51]:
df.head()

  train_serv  delay_dep  delayed  year  month  day       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day      date
0  SNCB/NMBS        -53    False  2014      1    1  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713       night  1-1-2014
1  SNCB/NMBS         11    False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257     morning  1-1-2014
2  SNCB/NMBS        197    False  2014      1    1                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595     morning  1-1-2014
3  SNCB/NMBS         -1    False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430     morning  1-1-2014
4  SNCB/NMBS        159    False  2014      1    1  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006   afternoon  1-1-2014

In [52]:
df["date"] = df["date"].apply(pd.to_datetime)

/var/folders/07/rfr15gnj2vx9fng2s7h5322h0000gn/T/ipykernel_48999/2707150541.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df["date"] = df["date"].apply(pd.to_datetime)

In [53]:
df.dtypes

train_serv                    object
delay_dep                      int64
delayed                         bool
year                           int64
month                          int64
day                            int64
destination_region            object
departure_region              object
temperature                  float64
relative_humidity            float64
wind_speed                   float64
wind_direction               float64
time_of_day                   object
date                  datetime64[ns]
dtype: object

In [54]:
df.tail()

        train_serv  delay_dep  delayed  year  month  day destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day       date
3183233  SNCB/NMBS        110    False  2022     12   31           FLANDERS  BRUSSELS-CAPITAL REGION    14.880943          65.271150   33.989033       208.46516       night 2022-12-31
3183234   THI-FACT         -3    False  2022     12   31           WALLONIA                 FLANDERS    15.650944          79.954200   36.881996       218.65982     morning 2022-12-31
3183235   THI-FACT        925     True  2022     12   31           FLANDERS                 FLANDERS    15.650944          79.954200   36.881996       218.65982     morning 2022-12-31
3183236   THI-FACT         40    False  2022     12   31           FLANDERS  BRUSSELS-CAPITAL REGION    15.600944          79.999855   37.008278       217.09283     morning 2022-12-31
3183237   THI-FACT        246    False  2022     12   31           FLANDERS                 FLANDERS    15.870944          78.782160   36.869694       215.86285     morning 2022-12-31

In [55]:
df["month"] = df["month"].map({1: "JAN", 2: "FEB", 3: "MAR", 4: "APR"
                , 5: "MAY", 6: "JUN", 7: "JUL", 8: "AUG", 9: "SEP"
                , 10: "OCT", 11: "NOV", 12: "DEC"})

In [58]:
df.head()

  train_serv  delay_dep  delayed  year month  day       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day       date
0  SNCB/NMBS        -53    False  2014   JAN    1  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713       night 2014-01-01
1  SNCB/NMBS         11    False  2014   JAN    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257     morning 2014-01-01
2  SNCB/NMBS        197    False  2014   JAN    1                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595     morning 2014-01-01
3  SNCB/NMBS         -1    False  2014   JAN    1  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430     morning 2014-01-01
4  SNCB/NMBS        159    False  2014   JAN    1  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006   afternoon 2014-01-01

In [59]:
df.drop(columns=["year", "day"], inplace=True)

In [60]:
df.head()

  train_serv  delay_dep  delayed month       destination_region         departure_region  temperature  relative_humidity  wind_speed  wind_direction time_of_day       date
0  SNCB/NMBS        -53    False   JAN  BRUSSELS-CAPITAL REGION                 WALLONIA     9.590943          84.870130   35.428463       185.24713       night 2014-01-01
1  SNCB/NMBS         11    False   JAN  BRUSSELS-CAPITAL REGION                 FLANDERS     6.050944          86.606674   23.784530       182.60257     morning 2014-01-01
2  SNCB/NMBS        197    False   JAN                 FLANDERS  BRUSSELS-CAPITAL REGION     5.240944          89.317700   21.749481       192.42595     morning 2014-01-01
3  SNCB/NMBS         -1    False   JAN  BRUSSELS-CAPITAL REGION                 FLANDERS     6.840944          83.881490   23.770906       178.26430     morning 2014-01-01
4  SNCB/NMBS        159    False   JAN  BRUSSELS-CAPITAL REGION                 FLANDERS     7.490944          82.104470   22.253124       170.69006   afternoon 2014-01-01

In [61]:
df.count()

train_serv            3182541
delay_dep             3182541
delayed               3182541
month                 3182541
destination_region    3182541
departure_region      3182541
temperature           3182541
relative_humidity     3182541
wind_speed            3182541
wind_direction        3182541
time_of_day           3182541
date                  3182541
dtype: int64

In [62]:
df.dtypes

train_serv                    object
delay_dep                      int64
delayed                         bool
month                         object
destination_region            object
departure_region              object
temperature                  float64
relative_humidity            float64
wind_speed                   float64
wind_direction               float64
time_of_day                   object
date                  datetime64[ns]
dtype: object

In [63]:
#export to pickle
df.to_pickle("/Users/ilseeb/Desktop/Postgraduate/Train Punctuality Data/df_train_delays.pkl")