In [9]:
#import libraries
import pandas as pd
import numpy as np

In [10]:
# import file
df = pd.read_pickle("/Users/ilseeb/Desktop/Postgraduate/Train Punctuality Data/final_df.pkl")

In [11]:
df.head()

,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,...,year,month,day,hour_time_dep,train_stations,region,temperature,relative_humidity,wind_speed,wind_direction
0,10,ICE,SNCB/NMBS,215,0/2,21:31:15,21:31:07,21:32:00,21:32:00,-45,...,20,1,1,22.0,BRUSSEL-ZUID,BRUSSELS-CAPITAL REGION,9.0,84.0,35.0,18.0
1,10,ICE,SNCB/NMBS,215,0/2,21:31:15,21:31:07,21:32:00,21:32:00,-45,...,20,1,1,22.0,BRUSSEL-ZUID,BRUSSELS-CAPITAL REGION,1.0,78.0,29.0,20.0
2,10,ICE,SNCB/NMBS,215,0/2,21:31:15,21:31:07,21:32:00,21:32:00,-45,...,20,1,1,22.0,BRUSSEL-ZUID,BRUSSELS-CAPITAL REGION,6.0,84.0,19.0,13.0
3,10,ICE,SNCB/NMBS,215,0/2,21:31:15,21:31:07,21:32:00,21:32:00,-45,...,20,1,1,22.0,BRUSSEL-ZUID,BRUSSELS-CAPITAL REGION,-0.0,93.0,19.0,21.0
4,10,ICE,SNCB/NMBS,215,0/2,21:31:15,21:31:07,21:32:00,21:32:00,-45,...,20,1,1,22.0,BRUSSEL-ZUID,BRUSSELS-CAPITAL REGION,5.0,91.0,22.0,26.0

In [12]:
df = df.drop(columns=["TRAIN_NO", "RELATION", "PTCAR_NO", "LINE_NO_DEP"
                    , "RELATION_DIRECTION", "LINE_NO_ARR", "PLANNED_DATE_ARR"
                    , "PLANNED_DATE_DEP", "REAL_DATE_ARR", "REAL_DATE_DEP"
                    ,"PTCAR_LG_NM_NL", "train_stations"])

In [13]:
df.head()

,TRAIN_SERV,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,DELAY_DEP,departure,destination,delayed,year,month,day,hour_time_dep,region,temperature,relative_humidity,wind_speed,wind_direction
0,SNCB/NMBS,21:31:15,21:31:07,21:32:00,21:32:00,-45,-53,HERGENRATH,BRUSSEL-ZUID,False,20,1,1,22.0,BRUSSELS-CAPITAL REGION,9.0,84.0,35.0,18.0
1,SNCB/NMBS,21:31:15,21:31:07,21:32:00,21:32:00,-45,-53,HERGENRATH,BRUSSEL-ZUID,False,20,1,1,22.0,BRUSSELS-CAPITAL REGION,1.0,78.0,29.0,20.0
2,SNCB/NMBS,21:31:15,21:31:07,21:32:00,21:32:00,-45,-53,HERGENRATH,BRUSSEL-ZUID,False,20,1,1,22.0,BRUSSELS-CAPITAL REGION,6.0,84.0,19.0,13.0
3,SNCB/NMBS,21:31:15,21:31:07,21:32:00,21:32:00,-45,-53,HERGENRATH,BRUSSEL-ZUID,False,20,1,1,22.0,BRUSSELS-CAPITAL REGION,-0.0,93.0,19.0,21.0
4,SNCB/NMBS,21:31:15,21:31:07,21:32:00,21:32:00,-45,-53,HERGENRATH,BRUSSEL-ZUID,False,20,1,1,22.0,BRUSSELS-CAPITAL REGION,5.0,91.0,22.0,26.0

In [16]:
df.describe(include="all")

,TRAIN_SERV,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,DELAY_DEP,departure,destination,delayed,year,month,day,hour_time_dep,region,temperature,relative_humidity,wind_speed,wind_direction
count,28630609,28630437,28630468,28629848,28629940,28630546.0,28630531.0,28630609,28630609,28630609,28630609.0,2.863061e+07,2.863061e+07,2.862994e+07,28630609,2.862994e+07,2.862994e+07,2.862994e+07,2.862994e+07
unique,5,73782,73830,5656,5491,7273.0,7318.0,294,432,2,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN
top,SNCB/NMBS,21:22:27,14:28:20,17:31:00,9:01:00,25.0,19.0,BRUSSEL-ZUID,BRUSSEL-ZUID,False,NaN,NaN,NaN,NaN,FLANDERS,NaN,NaN,NaN,NaN
freq,27845838,1107,1098,90061,75691,203364.0,171413.0,4424611,4432179,24769572,NaN,NaN,NaN,NaN,12829397,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,6.521725e+00,1.572273e+01,1.395109e+01,NaN,1.186595e+01,7.521791e+01,1.391407e+01,2.828546e+01
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.456058e+00,8.761111e+00,5.289513e+00,NaN,6.922533e+00,1.627477e+01,7.256728e+00,1.690809e+01
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,1.000000e+00,1.000000e+00,0.000000e+00,NaN,-9.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,3.000000e+00,8.000000e+00,9.000000e+00,NaN,7.000000e+00,6.400000e+01,8.000000e+00,1.900000e+01
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,7.000000e+00,1.600000e+01,1.400000e+01,NaN,1.200000e+01,7.900000e+01,1.300000e+01,2.300000e+01
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,1.000000e+01,2.300000e+01,1.800000e+01,NaN,1.700000e+01,8.900000e+01,1.800000e+01,3.100000e+01
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,1.200000e+01,3.100000e+01,2.300000e+01,NaN,3.900000e+01,9.900000e+01,5.400000e+01,9.900000e+01

: