Cleaning

In [42]:
#import libraries
import pandas as pd
import numpy as np

In [43]:
#download first file
df = pd.read_csv("/Users/ilseeb/Downloads/Train Punctuality Data/2014/Data_raw_punctuality_201401.csv")

In [44]:
#count how much data we have
df.count()

DATDEP                1900458
TRAIN_NO              1900458
RELATION              1900458
TRAIN_SERV            1900458
PTCAR_NO              1900458
LINE_NO_DEP           1806030
REAL_TIME_ARR         1806067
REAL_TIME_DEP         1806036
PLANNED_TIME_ARR      1806058
PLANNED_TIME_DEP      1806031
DELAY_ARR             1900458
DELAY_DEP             1900458
RELATION_DIRECTION          0
PTCAR_LG_NM_NL        1900458
LINE_NO_ARR           1806064
PLANNED_DATE_ARR      1806058
PLANNED_DATE_DEP      1806031
REAL_DATE_ARR         1806067
REAL_DATE_DEP         1806036
dtype: int64

In [45]:
df.head(100)

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP
0,01JAN2014,10,ICE,SNCB/NMBS,825,37,20:29:50,20:28:41,20:29:00,20:29:00,-19,-19,NaN,HERGENRATH,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014
1,01JAN2014,10,ICE,SNCB/NMBS,266,37,20:41:26,20:41:26,20:40:00,20:40:00,86,86,NaN,CHENEE,3,01JAN2014,01JAN2014,01JAN2014,01JAN2014
2,01JAN2014,10,ICE,SNCB/NMBS,27,37,20:42:26,20:42:30,20:41:00,20:41:00,86,90,NaN,ANGLEUR,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014
3,01JAN2014,10,ICE,SNCB/NMBS,726,36,20:45:41,20:47:14,20:44:00,20:46:00,101,74,NaN,LIEGE-GUILLEMINS,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014
4,01JAN2014,10,ICE,SNCB/NMBS,31,2,20:51:22,20:51:26,20:51:00,20:51:00,22,26,NaN,ANS,36,01JAN2014,01JAN2014,01JAN2014,01JAN2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,01JAN2014,112,IC/L,SNCB/NMBS,730,34,13:54:34,13:55:38,13:55:00,13:56:00,-26,-22,NaN,LIEGE-PALAIS,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
96,01JAN2014,112,IC/L,SNCB/NMBS,562,34,14:00:20,14:01:29,14:01:00,14:02:00,-40,-31,NaN,HERSTAL,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
97,01JAN2014,112,IC/L,SNCB/NMBS,835,34,14:06:29,14:07:00,14:07:00,14:07:00,-31,0,NaN,MILMORT,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
98,01JAN2014,112,IC/L,SNCB/NMBS,733,34L/1,14:08:40,14:09:01,14:11:00,14:12:00,-140,-179,NaN,LIERS,34,01JAN2014,01JAN2014,01JAN2014,01JAN2014
99,01JAN2014,112,IC/L,SNCB/NMBS,734,NaN,14:10:26,NaN,14:16:00,NaN,-334,0,NaN,LIERS-FAISCEAU,34L/1,01JAN2014,NaN,01JAN2014,NaN

In [46]:
#removed the trains which ended in Brussels
df['PTCAR_LG_NM_NL'][pd.isna(df.REAL_TIME_DEP)]

19             BRUSSEL-ZUID
39           LIERS-FAISCEAU
59           LIERS-FAISCEAU
99           LIERS-FAISCEAU
139          LIERS-FAISCEAU
                 ...
1900419    LIEGE-GUILLEMINS
1900430            KORTRIJK
1900433      MERELBEKE-T.W.
1900435    LIEGE-GUILLEMINS
1900457           OTTIGNIES
Name: PTCAR_LG_NM_NL, Length: 94422, dtype: object

In [47]:
#get final destination by grouping per train and date of departure
df['destination'] = df.groupby(['DATDEP', 'TRAIN_NO'], sort=False)['PTCAR_LG_NM_NL'].transform('last')

In [48]:
df.head(1220)

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,DELAY_ARR,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,destination
0,01JAN2014,10,ICE,SNCB/NMBS,825,37,20:29:50,20:28:41,20:29:00,20:29:00,-19,-19,NaN,HERGENRATH,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
1,01JAN2014,10,ICE,SNCB/NMBS,266,37,20:41:26,20:41:26,20:40:00,20:40:00,86,86,NaN,CHENEE,3,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
2,01JAN2014,10,ICE,SNCB/NMBS,27,37,20:42:26,20:42:30,20:41:00,20:41:00,86,90,NaN,ANGLEUR,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
3,01JAN2014,10,ICE,SNCB/NMBS,726,36,20:45:41,20:47:14,20:44:00,20:46:00,101,74,NaN,LIEGE-GUILLEMINS,37,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
4,01JAN2014,10,ICE,SNCB/NMBS,31,2,20:51:22,20:51:26,20:51:00,20:51:00,22,26,NaN,ANS,36,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,01JAN2014,1508,IC/L,SNCB/NMBS,1670,NaN,11:18:00,NaN,11:19:00,NaN,-60,0,NaN,GENK,21D,01JAN2014,NaN,01JAN2014,NaN,GENK
1216,01JAN2014,1509,IC/L,SNCB/NMBS,642,51B,NaN,9:06:04,NaN,9:04:00,0,124,NaN,KNOKKE,NaN,NaN,01JAN2014,NaN,01JAN2014,GENK
1217,01JAN2014,1509,IC/L,SNCB/NMBS,337,51B,9:09:04,9:09:54,9:07:00,9:07:00,124,174,NaN,DUINBERGEN,51B,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK
1218,01JAN2014,1509,IC/L,SNCB/NMBS,540,51B,9:12:54,9:13:11,9:11:00,9:11:00,114,131,NaN,HEIST,51B,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK
1219,01JAN2014,1509,IC/L,SNCB/NMBS,214,51,9:22:29,9:22:29,9:20:00,9:20:00,149,149,NaN,BRUGGE-DIJK,51,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK

In [50]:
#get only rows where the train departed from BRUSSEL-CENTRAAL
df2 = df[df.PTCAR_LG_NM_NL == 'BRUSSEL-CENTRAAL']

In [51]:
df2.count()

DATDEP                31422
TRAIN_NO              31422
RELATION              31422
TRAIN_SERV            31422
PTCAR_NO              31422
LINE_NO_DEP           31422
REAL_TIME_ARR         31422
REAL_TIME_DEP         31422
PLANNED_TIME_ARR      31422
PLANNED_TIME_DEP      31422
DELAY_ARR             31422
DELAY_DEP             31422
RELATION_DIRECTION        0
PTCAR_LG_NM_NL        31422
LINE_NO_ARR           31422
PLANNED_DATE_ARR      31422
PLANNED_DATE_DEP      31422
REAL_DATE_ARR         31422
REAL_DATE_DEP         31422
destination           31422
dtype: int64

In [55]:
#add column to define if train was delayed or not
df2['delayed'] = np.where(df2['DELAY_DEP'] > 360, True, False)

/var/folders/07/rfr15gnj2vx9fng2s7h5322h0000gn/T/ipykernel_23189/3683751268.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['delayed'] = np.where(df2['DELAY_DEP'] > 360, True, False)

In [56]:
df2.head(100)

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,...,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,destination,delayed
17,01JAN2014,10,ICE,SNCB/NMBS,215,0/2,21:31:15,21:31:07,21:32:00,21:32:00,...,-53,NaN,BRUSSEL-CENTRAAL,0/2,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,False
288,01JAN2014,1209,INT,SNCB/NMBS,215,0/6,9:58:51,10:01:11,9:59:00,10:01:00,...,11,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,False
313,01JAN2014,1210,INT,SNCB/NMBS,215,0/5,7:02:34,7:04:17,6:59:00,7:01:00,...,197,NaN,BRUSSEL-CENTRAAL,0/5,01JAN2014,01JAN2014,01JAN2014,01JAN2014,ESSEN,False
370,01JAN2014,1213,INT,SNCB/NMBS,215,0/6,10:57:53,11:00:59,10:59:00,11:01:00,...,-1,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,False
401,01JAN2014,1217,INT,SNCB/NMBS,215,0/6,11:58:12,12:03:39,11:59:00,12:01:00,...,159,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5429,01JAN2014,1928,IC/L,SNCB/NMBS,215,0/6,7:15:24,7:16:28,7:15:00,7:16:00,...,28,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,MOESKROEN,False
5449,01JAN2014,1929,IC/L,SNCB/NMBS,215,0/6,8:15:15,8:16:28,8:15:00,8:16:00,...,28,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,MOESKROEN,False
5469,01JAN2014,1930,IC/L,SNCB/NMBS,215,0/6,9:15:21,9:16:20,9:15:00,9:16:00,...,20,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,MOESKROEN,False
5489,01JAN2014,1931,IC/L,SNCB/NMBS,215,0/6,10:15:25,10:16:25,10:15:00,10:16:00,...,25,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,MOESKROEN,False
5509,01JAN2014,1932,IC/L,SNCB/NMBS,215,0/6,11:15:07,11:16:21,11:15:00,11:16:00,...,21,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,MOESKROEN,False

In [59]:
df2[df2['delayed'] == True]

,DATDEP,TRAIN_NO,RELATION,TRAIN_SERV,PTCAR_NO,LINE_NO_DEP,REAL_TIME_ARR,REAL_TIME_DEP,PLANNED_TIME_ARR,PLANNED_TIME_DEP,...,DELAY_DEP,RELATION_DIRECTION,PTCAR_LG_NM_NL,LINE_NO_ARR,PLANNED_DATE_ARR,PLANNED_DATE_DEP,REAL_DATE_ARR,REAL_DATE_DEP,destination,delayed
406,01JAN2014,1218,INT,SNCB/NMBS,215,0/5,9:14:08,9:15:58,8:59:00,9:01:00,...,898,NaN,BRUSSEL-CENTRAAL,0/5,01JAN2014,01JAN2014,01JAN2014,01JAN2014,ESSEN,True
782,01JAN2014,1249,INT,SNCB/NMBS,215,0/6,20:11:55,20:14:52,19:59:00,20:01:00,...,832,NaN,BRUSSEL-CENTRAAL,0/6,01JAN2014,01JAN2014,01JAN2014,01JAN2014,BRUSSEL-ZUID,True
1107,01JAN2014,1506,IC/L,SNCB/NMBS,215,0/3,7:46:34,7:47:46,7:39:00,7:40:00,...,466,NaN,BRUSSEL-CENTRAAL,0/3,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK,True
1527,01JAN2014,1516,IC/L,SNCB/NMBS,215,0/3,17:46:08,17:48:36,17:39:00,17:40:00,...,516,NaN,BRUSSEL-CENTRAAL,0/3,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK,True
1569,01JAN2014,1517,IC/L,SNCB/NMBS,215,0/3,18:46:10,18:48:35,18:39:00,18:40:00,...,515,NaN,BRUSSEL-CENTRAAL,0/3,01JAN2014,01JAN2014,01JAN2014,01JAN2014,GENK,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900062,31JAN2014,17911,EXTRA,SNCB/NMBS,215,0/3,9:32:09,9:32:09,9:18:00,9:18:00,...,849,NaN,BRUSSEL-CENTRAAL,0/3,31JAN2014,31JAN2014,31JAN2014,31JAN2014,SCHAARBEEK-T.W./E.,True
1900327,31JAN2014,17947,EXTRA,SNCB/NMBS,215,0/3,20:27:01,20:27:42,19:28:00,19:28:00,...,3582,NaN,BRUSSEL-CENTRAAL,0/3,31JAN2014,31JAN2014,31JAN2014,31JAN2014,SCHAARBEEK-BUNDEL L,True
1900362,31JAN2014,17924,EXTRA,SNCB/NMBS,215,0/6,20:07:07,20:07:38,19:25:00,19:25:00,...,2558,NaN,BRUSSEL-CENTRAAL,0/6,31JAN2014,31JAN2014,31JAN2014,31JAN2014,BRUSSEL-ZUID,True
1900367,31JAN2014,17926,EXTRA,SNCB/NMBS,215,0/5,20:36:47,20:36:47,20:11:00,20:11:00,...,1547,NaN,BRUSSEL-CENTRAAL,0/5,31JAN2014,31JAN2014,31JAN2014,31JAN2014,ANTWERPEN-NOORD-BUNDEL N,True
1900443,31JAN2014,17953,EXTRA,SNCB/NMBS,215,0/3,23:58:59,23:58:52,23:45:00,23:45:00,...,832,NaN,BRUSSEL-CENTRAAL,0/3,31JAN2014,31JAN2014,31JAN2014,31JAN2014,OTTIGNIES,True

In [60]:
pip install openpyxl

2033.79s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from openpyxl) (1.1.0)
WARNING: You are using pip version 21.2.3; however, version 22.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [61]:
pd.DataFrame(df2['destination'].unique()).to_excel("/Users/ilseeb/Downloads/Train Punctuality Data/train_stations.xlsx")